### DISCUSSION TITLE
Heat Compensation Curve adjustments?

### DISCUSSION THREAD

**Discussion by dehoej** [gekkekoe/esphome-ecodan-hp#125] [Announcements]
I am seeking assistance with integrating my Mitsubishi Ecodan EHSD-YM9D heat pump using the ESPHome Ecodan integration. Our setup includes an outdoor unit and a 200L buffer tank, installed in an older house featuring both underfloor heating and radiators. Notably, the underfloor heating operates as a separate system, independent of the heat pump.

We utilize the heating curve, adjusted based on outdoor temperature, typically set to minus 5 relative to the curve. However, during windy conditions, the supply temperature often falls short, leading to insufficient heating. To address this, I aim to adjust the heating curve dynamically in response to wind conditions.

I had anticipated that the ESPHome integration would allow for such adjustments, but I have not found a method to modify the heating curve as I can through the heat pump's interface. Is it correct that this functionality is currently unavailable in the ESPHome integration? If so, are there any recommended approaches or workarounds to achieve dynamic adjustments to the heating curve based on environmental factors like wind?

**Comment by gekkekoe** [comment]
With heat curve the feed temp is determined by your curve and outside temperature. On the main ftc controller you can do +/- a couple of degrees. But this is not available over the cn105.

You can set it to heat flow and manage your own heat curve?

If you want to do some fancy dynamic curve yout can try something like this (small proof of concept I made a while ago):

`get_flow_temp.py`
```python
# determine own curve table, keep in mind that the first (outside) temp component must not overlap
temp_table = [
    (0, 30),        # below 0c -> 30c feed temp
    (1, 29.5),      # between 0c - 1c -> 30c-29.5c
    (2, 29),        # between 1c - 2c -> 29.5c-29c
    (3, 28.5),      # above 3c -> 28.5c
]

outside_temp = data.get("outside_temp")
target_temp = temp_table[0][1]

for i in range(len(temp_table)):
    if outside_temp > temp_table[i][0]:
        target_temp = temp_table[i][1]
    else:
        # determine new feed temp between 2 points in the table
        target_temp = (target_temp + temp_table[min(len(temp_table)-1, i)][1]) / 2
        # round to nearest 0.5c
        target_temp = round(target_temp * 2) / 2
        break

output['new_flow_temp'] = target_temp
```
see https://www.home-assistant.io/integrations/python_script/ for enabling python scripts. You need to pass in your wind conditions (like I did with the outside temp) and determine new feed temp. If you can determine the new flow temp without such a table, then it's even easier. 

The automation below is only active in heatflow mode and will adjust feed temp according to the python logic. It's currently triggered on change of the outside temperature, so you probably want this to be triggered on wind condition change as well.
```yaml
# weather compensation curve automations
- id: HeatpumpAdjustFlowSetpointForOutsideTemp
  alias: Set flow temp depending on outside temperature
  trigger:
    - trigger: state
      entity_id:
        - sensor.ecodan_heatpump_outside_temp
  condition:
    - condition: template
      value_template: >
        {{ not (states('binary_sensor.ecodan_heatpump_defrost') | default(false) ) and states('select.ecodan_heatpump_selected_operating_mode') == state_attr('select.ecodan_heatpump_selected_operating_mode', 'options')[1] }}
  action:
    - action: python_script.get_flow_temp
      response_variable: get_flow_temp_output
      data:
        outside_temp: "{{ (states('sensor.ecodan_heatpump_outside_temp') | float(0)) }}"
    - action: climate.set_temperature
      data:
        entity_id: climate.ecodan_heatpump_zone_1_climate
        temperature: "{{ get_flow_temp_output['new_flow_temp'] }}"
```
