### DISCUSSION TITLE
Water return temperature unstable

### DISCUSSION THREAD

**Discussion by MrBretze** [gekkekoe/esphome-ecodan-hp#136] [General]
Hello, I don't know if it is my configuration, but the water return temperature has randomly set to 25° then returns to the correct temperature like the screen
![Image](https://github.com/user-attachments/assets/9823954b-07df-4ddc-bcf3-fb6df48190cf)

**Comment by gekkekoe** [comment]
Please ask questions in the discussion section. The return temperature isn't a setting that is set by the ESP. Your heatpump probably stopped, then the temp in your pipe temp will go down (decay). In the morning it starts again. Plot the operating mode then it should be clear. 

I'm going to move this to questions

**Comment by DamijanD** [comment]
@MrBretze you should compare this history with Zone info (idle/both), Mode (heating,...), Water pump status (on/off). What was your flow temperature?

**Comment by MrBretze** [comment]
I think you misunderstood me, sorry...
It's not a misunderstanding on my part, but a bug.
The sensor that returns the water temperature returns to 25° (see my screenshot) every 3/5 seconds and immediately returns to the correct temperature... the average is fair and correct, it was just to warn you...

**Comment by MrBretze** [comment]
A little video to show you the problems 
https://github.com/user-attachments/assets/00da1fd4-5a9e-4efe-815d-3cff1ceb45b3

**Reply by gekkekoe** [reply]
Ah you should have posted this directly. Are you able to produce log with uart logging ? Update to latest build and see if it is still occurring. I have never seen this before. I did notice that the 25c was refreshed really fast afterwards, makes me think the refresh rate might be too high for your system. Did you adjust the default refresh rate ?

Is the feed temp (Temp départ) behaving the same ? It's in the same message.

I suspect that this is actually reported by the heatpump. It could be overloaded by the high refresh rate, but try to log the events

**Reply by MrBretze** [reply]
Hello, the feed temp does not have this problem.
Actually, I have updated to the last build and the problem is still occurring.
The refresh rate is actually the default, but I can increase this one
I try to produce log later... sorry

This is my configuration, actually with ESPHome 2024.12.4.

```yaml
substitutions:
  name: ecodan-heatpump
  friendlyName: Ecodan heatpump

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

# Enable logging
logger:
  baud_rate: 0
  logs:
    esp32.preferences: ERROR
    sensor: ERROR
    text_sensor: ERROR
    binary_sensor: ERROR
    switch: ERROR
    button: ERROR
    number: ERROR
    climate: ERROR
    component: ERROR
    ecodan.component: ERROR

# Enable Home Assistant API
api:
  reboot_timeout: 0s
# encryption:
#    key: "key"

ota:
  - platform: esphome
    password: "pass"

wifi:
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.XXX
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ecodan-Pump Fallback Hotspot"
    password: "krNhJMA985yF"

external_components:
  - source: github://gekkekoe/esphome-ecodan-hp@main
    components: [ ecodan ]
    refresh: always

packages:
  remote_package:
    url: https://github.com/gekkekoe/esphome-ecodan-hp/
    ref: main
    refresh: always
    files: [ 
            confs/base.yaml,
            confs/esp32s3.yaml, # confs/esp32.yaml, for regular board
            confs/zone1.yaml,
            ## enable if you want to use zone 2
            #confs/zone2.yaml,
            ## enable label language file
            #confs/ecodan-labels-en.yaml,
            #confs/ecodan-labels-nl.yaml,
            #confs/ecodan-labels-it.yaml,
            confs/ecodan-labels-fr.yaml,
            #confs/ecodan-labels-es.yaml,
            #confs/server-control.yaml,
            #confs/debug.yaml
            confs/wifi.yaml
            #confs/status_led_rgb.yaml
           ]

web_server:
  port: 80
  #ota: true


ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan
```

**Reply by gekkekoe** [reply]
if the feed temp is stable then its not the cn105 message. So It must come from your heatpump itself. I would suggest checking the wire for the return sensor (thw2), look in the service manual where its located. It could be a loose connector. Mines is connected on CNW12

25c is the 'defualt' temp that is reported by the heatpump when no thermistor is fitted. You can also monitor this sensor from the main screen, but it seems that it updates way too fast to be observed there.

Else we need to get logging, but my best guess is your thermistor is faulty/loose fitting (because the feed temp would also cause problems is the message was the case).

You can try and see if the DHW tank is also stable? It's in the same message as well.

**Reply by MrBretze** [reply]
Ok, I check this later and I don't have a DHW Tank because I already had a thermodynamic hot water tank before the replacement of the boiler

**Reply by gekkekoe** [reply]
You could try lowering the polling rate, though I don't think this is the issue, it might masked/hide it. But I think you might have a hardware issue

```yaml
ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan
# polling interval override in ms, default 500
  polling_interval_override: 1000
```
