### DISCUSSION TITLE
Testers needed with FTC7 inside units

### DISCUSSION THREAD

**Discussion by gekkekoe** [gekkekoe/esphome-ecodan-hp#137] [General]
We can get outside unit thermistor values without service codes on FTC7 units. The following set can be retrieved on FTC7:

```
004 Discharge temp (TH4)
005 liquid pipe 1 temp (TH3)
007 two phase pipe temp (TH6)
008 suction pipe temp (TH32)
010 heatsing temp (TH8)
011 compressor surface temp (TH33) 
012 discharge superheat
013 subcool
```

I made a dev branch that does this. It detects what FTC version is present and will query the data without having to use an expensive service code call. Only compressor starts and fan speed are still being retrieved via service code calls.

FTC6/5 users will only have access to following outside unit thermistor values. It takes up to 5s to perform a service call and thats why I only retrieve the Interesting ones for FTC5/6.  Fan speed and compressor starts are also available.
```
004 Discharge temp (TH4)
005 liquid pipe 1 temp (TH3)
007 two phase pipe temp (TH6)
```

To test, edit your `ecodan-esphome.yaml` to use the dev branch:

```yaml
external_components:
  - source: github://gekkekoe/esphome-ecodan-hp@dev
    components: [ ecodan ]
    refresh: always

packages:
  remote_package:
    url: https://github.com/gekkekoe/esphome-ecodan-hp/
    ref: dev
```

Once running, test the reported values against your main controller screen. I don't have a FTC7, so I need users to test this.
BTW: I used google translate for languages other than Dutch and English. Corrected translations are highly appreciated.
