### DISCUSSION TITLE
Compilation error trying to update

### DISCUSSION THREAD

**Discussion by limkinZero** [gekkekoe/esphome-ecodan-hp#140] [Announcements]
Hi all,

Today, i tryed update my esp32 board with the last changes but i´m compilation errores. Some suggestion?

![image](https://github.com/user-attachments/assets/228e2a07-3e28-4c2f-b555-d8b36f2b7e2e)

My ecodan config is (i have overwritte TX and RX pins):

```yaml
substitutions:
  name: mitsubishi-ecodan
  friendlyName: Mitsubishi Ecodan
# heatpump heating/cooling switch
  default_heating_switch_mode: HEAT_ROOM_TEMP
  default_cooling_switch_mode: COOL_FLOW_TEMP

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

ota:
  - platform: esphome

api:
  reboot_timeout: 0s

external_components:
  - source: github://gekkekoe/esphome-ecodan-hp@main
    components: [ ecodan ]
    refresh: always

packages:
  remote_package:
    url: https://github.com/gekkekoe/esphome-ecodan-hp/
    ref: main
    refresh: always
    files: [ 
            confs/base.yaml,            # required
            confs/request-codes.yaml,   # disable if your unit does not support request codes (service menu)
            confs/esp32.yaml,           # confs/esp32.yaml, for regular board
            #confs/esp32s3-led.yaml,    # atom s3 status leds
            confs/zone1.yaml,
            ## enable if you want to use zone 2
            #confs/zone2.yaml,
            ## enable label language file
            confs/ecodan-labels-en.yaml,
            confs/server-control.yaml,
            #confs/debug.yaml,
            ## enable this to monitor WiFi status with ESP in-built LED
            #confs/status_led.yaml,
            ## enable this to monitor status with custom led colors, uses https://github.com/esphome/esphome/pull/5814
            #confs/status_led_rgb.yaml,
            confs/wifi.yaml
           ]

# enable logger
logger:
  baud_rate: 115200
  logs:
    esp32.preferences: ERROR
    sensor: ERROR
    text_sensor: ERROR
    binary_sensor: ERROR
    switch: ERROR
    button: ERROR
    number: ERROR
    climate: ERROR
    component: ERROR
    ecodan.component: ERROR

# Enable Web server.
web_server:
  port: 80
  #ota: true

uart:
  id: uart_ecodan
  rx_pin:
    number: GPIO26
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO27
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic

ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan
```
