### DISCUSSION TITLE
flash read err on atom lite

### DISCUSSION THREAD

**Discussion by lebphi** [gekkekoe/esphome-ecodan-hp#154] [Announcements]
hi,

i've followed the procedure in https://github.com/gekkekoe/esphome-ecodan-hp/blob/main/docs/install-from-bin.md to install esp32s3-z1-fr-2025-05-08.1.factory.bin on a atom lite module (https://docs.m5stack.com/en/core/ATOM%20Lite). 

Atfer flashing with https://web.esphome.io/?dashboard_install on chrome i've this message on logs :

[07:49:30]rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[07:49:30]flash read err, 1000
[07:49:30]ets_main.c 371 
[07:49:30]ets Jun  8 2016 00:22:57

is the problem come from my atom lite not compatible with the factory.bin ? If yes where i can find the good version of the factory.bin ?
or the problem come from other thing ?

if i flash with "prepare for first use" all is ok.

thank you for youer help.

philippe

**Comment by gekkekoe** [comment]
Only the atom S3 lite is supported by the prebuilt firmwares.

Follow https://github.com/gekkekoe/esphome-ecodan-hp/blob/main/docs/build-from-source.md and build a firmware for your own board. Configure 26 and 32 as pins.

You can't use any of the predefined boards and need to put something like this in main yaml
```yaml
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

uart:
  id: uart_ecodan
  rx_pin:
    number: GPIO26
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO32
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
```

(or just buy the correct atom S3 lite)
